詳細データ取得
planb369/backend-practice-app pull request #2
Opened 2023-11-08 01:46 UTC by planb369

2023-11-08 01:51 UTC, sho-pb requested changes

2023-11-08 01:51 UTC, sho-pb commented on models/noteModel.ts
> +      db.query(`SELECT*FROM notes where id=${id}`, (error, results) => {
sql injectionされます。

2023-11-08 01:51 UTC, sho-pb commented on controllers/noteController.ts
> +      const result = await Note.find(id);
データがないときは404にする
1. ErrorクラスをextendしたNotFoundErrorというclassを作成し、それをthrowする
2. catchでif (err instance of NotFoundError) の時に404ステータスを返却する

res.statusの500や404などは定数にすること

2023-11-08 01:51 UTC, sho-pb commented on routes/noteRoutes.ts
> +  const id = req.params.id;
ここでidを渡さない。ルーティングの定義のみにすること
Controllerの中でidを取得するようにしてください

2023-11-08 01:51 UTC, sho-pb commented on models/noteModel.ts
> +      db.query(`SELECT*FROM notes where id=${id}`, (error, results) => {
SELECT*FROM notes where id=
読みにくいです

SELECT * FROM notes where id =

2023-11-08 01:58 UTC, sho-pb commented on models/noteModel.ts
> +        return resolve(results);
EntityにMappingされてないですね。

2023-11-08 02:10 UTC, planb-sakai commented on models/noteModel.ts
> +      db.query(`SELECT*FROM notes where id=${id}`, (error, results) => {
SQLの予約語を大文字に統一してほしいです
```sql
SELECT * FROM notes WHERE id =
```

2023-11-08 05:19 UTC, planb-sakai commented on controllers/noteController.ts
> +const httpStatus_internalServerError = 500;
こんな定義のほうが望ましいかもしれません。
```ts
const HTTP_STATUS = {
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
};
```
定数は単語大文字でアンダースコア(_)で区切ることが多いです。

2023-11-08 05:19 UTC, planb-sakai commented on controllers/noteController.ts
> +const httpStatus_internalServerError = 500;
あと別のControllerでも使う可能性があるので別ファイルで定義したほうがいいです

2023-11-08 05:20 UTC, sho-pb requested changes

2023-11-08 05:20 UTC, sho-pb commented on controllers/noteController.ts
> +const httpStatus_internalServerError = 500;
- 他のコントローラーでも使用したくなったらどうしますか？
- 定数の命名は大文字 + スネークケースで定義することが多いです。
https://qiita.com/RyosukeSomeya/items/90f8e780b37c53758276

2023-11-08 05:20 UTC, sho-pb commented on models/noteModel.ts
> +        "SELECT*FROM notes where id=?",
指摘内容が改善されていません。

2023-11-08 05:24 UTC, planb-sakai commented on models/noteModel.ts
> +import * as mysql from "mysql2/";
`import * as mysql from "mysql2/";` の `/` って必要でしょうか？

2023-11-08 05:27 UTC, sho-pb commented on controllers/noteController.ts
> +      return res.status(httpStatus_badRequest).json({
Errorをthrowしてcatchに飛ばしてください

2023-11-08 05:29 UTC, sho-pb commented on httpStatus.ts
> +export const HTTP_STATUS = {
ディレクトリを整理してください。

2023-11-08 05:33 UTC, sho-pb commented on controllers/noteController.ts
> +        return res.status(HTTP_STATUS.NOT_FOUND).json({
if (err instanceof Error) の時は、consoleにログを出力しているが、こちらでは、consoleを出していないのはなぜ？

2023-11-08 07:23 UTC, sho-pb commented on controllers/noteController.ts
> +        console.error("404 NotFoundError : ", err.message);
エラーメッセージも定数化しといたほうがいいですね。

2023-11-09 09:43 UTC, sho-pb commented on controllers/NoteController.ts
> +        total: results.length,
ここのデータはresultのlengthではなく、notesのトータルにしたい

例）
DB ... 20件存在
limit ... 10件のみ取得
total = DBの20件をtotalとする

2023-11-09 09:44 UTC, sho-pb commented on controllers/NoteController.ts
> +        throw new MethodNotAllowedError("許可されていないHTTPメソッドです");
これは不要かな。router.tsのroute.getで指定しているmethodでしかアクセスできないはずなので

2023-11-09 10:07 UTC, planb-sakai commented on controllers/NoteController.ts
> +      const slicedResults = results.slice(offset, offset + limit);
SQL(DB)ではなくプログラム側でoffsetとlimitをかけているのはなぜ？？
DBでかけたほうがいいと思います（offset遅い問題はありますが）

2023-11-15 02:06 UTC, sho-pb approved these changes

2023-11-15 02:09 UTC, planb-sakai approved these changes
LGTM

2023-11-15 02:09 UTC, planb-sakai commented on models/NoteModel.ts
> +          return resolve(results[0]["COUNT(id)"]);
今回はOKですが
`SELECT COUNT(id) as count FROM notes`
というようにしておくと
`results[0]["count"]` のように比較的認知しやすくなると思います

2023-11-15 02:17 UTC, merged