編集機能
planb369/backend-practice-app pull request #4
Opened 2023-11-16 07:06 UTC by planb369

2023-11-16 07:12 UTC, planb-sakai commented on models/NoteModel.ts
> +      const mysqlTimestamp = generateMysqlCurrentTime();
MySQLに現在時刻を取得する関数があるので、外から渡さずSQLで直接呼び出しください

2023-11-16 07:18 UTC, planb-sakai commented on models/NoteModel.ts
> +  static checkNoteExists(id: string): Promise<number> {
個人的にはbooleanで返したい気持ち

2023-11-16 07:24 UTC, planb-sakai commented on models/NoteModel.ts
> +      const mysqlTimestamp = generateMysqlCurrentTime();
あ、これ前回のエンドポイントで見逃してたか。すみません

2023-11-16 08:17 UTC, sho-pb requested changes

2023-11-16 08:17 UTC, sho-pb commented on controllers/NoteController.ts
> +      const isExists = await NoteModel.checkNoteExists(id);
これ、findの結果がnullかどうかでも判断できそうですね

2023-11-16 08:17 UTC, sho-pb commented on models/NoteModel.ts
> +  static putNote(
updateの方が良いですね

2023-11-16 08:17 UTC, sho-pb commented on models/NoteModel.ts
> +    id: string,
引数にNoteModelを受け取る方が綺麗かも、、、postの方も

2023-11-16 08:19 UTC, sho-pb commented on models/NoteModel.ts
>    static postNote(title: string, content: string): Promise<NoteModel> {
save

2023-11-16 08:22 UTC, sho-pb commented on models/NoteModel.ts
>    static postNote(title: string, content: string): Promise<NoteModel> {
```ts
const note = new NoteModel();
note.title = 'xxx';

NoteModel.save(note);

class NoteModel {
  find(id: string): NoteModel {}

  static create(note: NoteModel): NoteModel {

  }

  static update(note: NoteModel): NoteModel {}
}
```

2023-11-22 01:28 UTC, sho-pb commented on controllers/NoteController.ts
> +      const isExists = await NoteModel.findNote(id);
isExistsはBool値と考えられそうな命名だが、実際にはNoteMotelが入っており、紛らわしい

2023-11-22 01:39 UTC, sho-pb commented on controllers/NoteController.ts
> +      const findNote = await NoteModel.findNote(id);
変数名に動詞を使用するのは適切ではない。

2023-11-22 01:47 UTC, planb-sakai commented on controllers/NoteController.ts
> +        );
APIをリクエストした側ではなく、内部処理で失敗した可能性が高いのでサーバー側の内部処理エラー(500)として扱いたいです。

2023-11-22 01:49 UTC, sho-pb commented on controllers/NoteController.ts
> +      const foundNote = await NoteModel.findNote(id);
シンプルに、noteっていう変数名にすればいいと思います

2023-11-22 01:50 UTC, sho-pb commented on controllers/NoteController.ts
> +      const note = new NoteModel();
そして、ここでnewするのではなく、↑で取得したnoteのpropertyを変えればいい。

2023-11-22 02:22 UTC, sho-pb commented on controllers/NoteController.ts
> +      if (note === null) {
JavaScript(TypeSCript)においてはほとんどの場合、
```js
if (!note) 
```
（論理否定）でOK

2023-11-22 02:25 UTC, sho-pb approved these changes
lgtm

2023-11-22 02:26 UTC, planb-sakai approved these changes
LGTM

2023-11-22 02:30 UTC, merged